// Generated by CoffeeScript 1.7.1
var list, list_searcher, sort_list;

sort_list = function(numbers) {
  var sorted;
  sorted = numbers.sort(function(a, b) {
    return a - b;
  });
  return sorted;
};

list_searcher = function(needle, haystack, sorter) {
  'Requires a needle, haystack, and a function that sorts the haystack.\nReturns the index in the sorted array of needle if found,\nelse returns false';
  var found, sorted_haystack;
  sorted_haystack = sorter(haystack);
  found = sorted_haystack.indexOf(needle);
  if (found === -1) {
    return false;
  } else {
    return found;
  }
};

list = [1, 3, 10, -100, 2, 1, 53, 0];

console.log(sort_list(list));

console.log(list_searcher(2, list, sort_list));

console.log(sort_list(list));

console.log(list_searcher(13, list, sort_list));
