// Generated by CoffeeScript 1.7.1
var fs, store_data;

fs = require('fs');

store_data = 'a';

fs.readFile('store.json', 'ascii', function(err, data) {
  var get_products_for, get_stores_stocking_cd, store;
  if (err) {
    throw err;
  }
  store = JSON.parse(data);
  get_products_for = function(name, branch, store_data) {
    var merch, merchandise, stock, _i, _j, _len, _len1, _ref;
    stock = "" + name + " at " + branch + " has the following stock: \n";
    merch = ['books', 'cds'];
    _ref = store_data['stock'];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      store = _ref[_i];
      if (store.name === name && store.branch === branch) {
        for (_j = 0, _len1 = merch.length; _j < _len1; _j++) {
          merchandise = merch[_j];
          stock += "   " + merchandise + ": ";
          if (store.hasOwnProperty(merchandise)) {
            stock += store[merchandise].join(', ');
          } else {
            stock += "None";
          }
          stock += "\n";
        }
      }
    }
    return stock;
  };
  get_stores_stocking_cd = function(cd, store_data) {
    var merch_type, stores_in_stock, who_has_stock, _i, _j, _len, _len1, _ref;
    merch_type = 'cds';
    stores_in_stock = [];
    who_has_stock = '';
    _ref = store_data["stock"];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      store = _ref[_i];
      if (store.hasOwnProperty(merch_type) && store[merch_type].indexOf(cd) > -1) {
        stores_in_stock.push({
          name: store.name,
          branch: store.branch
        });
      }
    }
    if (stores_in_stock.length > 0) {
      who_has_stock += "The following stores have stock of " + cd + ":\n";
      for (_j = 0, _len1 = stores_in_stock.length; _j < _len1; _j++) {
        store = stores_in_stock[_j];
        who_has_stock += "  " + store.name + " at " + store.branch + "\n";
      }
    } else {
      who_has_stock += "No stores have stock of " + cd + ". Have you considered iTunes?";
    }
    return who_has_stock;
  };
  console.log(get_products_for('Exclusive Books', 'Soweto', JSON.parse(data)));
  console.log(get_stores_stocking_cd('Creed', JSON.parse(data)));
  console.log(get_stores_stocking_cd('Nine Inch Nails', JSON.parse(data)));
  return console.log(get_stores_stocking_cd('Britney Spears', JSON.parse(data)));
});
