// Generated by CoffeeScript 1.7.1
var random, randoms, sort_list, _i;

sort_list = function(numbers) {
  var sorted;
  sorted = numbers.sort(function(a, b) {
    return a - b;
  });
  return sorted;
};

console.log(sort_list([3, 2, 1]));

console.log(sort_list([3, 10, 2, 1, 53, 0]));

console.log(sort_list([-1, 3, 10, -100, 2, 1, 53, 0]));

randoms = [];

for (random = _i = 0; _i <= 25; random = ++_i) {
  randoms.push(1000 * Math.random(random) + 1);
}

console.log(sort_list(randoms));
