// Generated by CoffeeScript 1.7.1
var string_converter;

string_converter = function(str) {
  var char_index, new_string, num_index, str_part, str_parts, _i, _len;
  if (!(str.length >= 5)) {
    throw "Too short, your string (" + str + ") must be more than 5 characters";
  }
  if (!(str.length <= 40)) {
    throw "Too long, your string (" + str + ") must be less than 40 characters";
  }
  char_index = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z'];
  num_index = ['zero', 'one', 'two', 'three', 'four', 'five', 'six', 'seven', 'eight', 'nine'];
  str_parts = str.split('');
  new_string = '';
  for (_i = 0, _len = str_parts.length; _i < _len; _i++) {
    str_part = str_parts[_i];
    if (str_part.match(/[a-zA-z]/)) {
      new_string += char_index.indexOf(str_part.toLowerCase());
    } else {
      new_string += num_index[str_part];
    }
  }
  return new_string;
};

console.log(string_converter('Abc12'));

console.log(string_converter('foo123Bar'));

console.log(string_converter('BAZ5678qux'));
